ARG UBUNTU_VERSION=24.04
ARG TARGETARCH=amd64
ARG GO_RELEASE

FROM scratch AS integration-tests-base
LABEL mock.component="integration-tests-base" \
      mock.go_version="${GO_RELEASE}" \
      mock.targetarch="${TARGETARCH}" \
      mock.ubuntu="${UBUNTU_VERSION}"

